"""
Static seed data for public recruiting & networking events.
Covers April–August 2026 Toronto finance recruiting season.
"""
from datetime import datetime

EVENTS = [
    # ── April 2026 ─────────────────────────────────────────────────────────
    {
        "firm_name": "TD Securities",
        "event_type": "Networking",
        "title": "TD Securities Summer Analyst Networking Night",
        "date": datetime(2026, 4, 18, 18, 0),
        "location": "TD Centre, 66 Wellington St W, Toronto",
        "description": "An evening of networking with TD Securities professionals across IBD, Capital Markets, and Global Markets. Open to 3rd and 4th year students.",
        "is_public": True,
    },
    {
        "firm_name": "Rotman Commerce Career Centre",
        "event_type": "Info Session",
        "title": "Breaking into Investment Banking — Career Panel",
        "date": datetime(2026, 4, 19, 12, 30),
        "location": "Rotman Commerce, 105 St George St, Room 140",
        "description": "Rotman Commerce alumni and professionals from RBC, BMO, and CIBC discuss their paths into IBD, what recruiters look for, and how to stand out.",
        "is_public": True,
    },
    {
        "firm_name": "UofT Finance Club",
        "event_type": "Networking",
        "title": "Finance Club Speed Networking Sessions",
        "date": datetime(2026, 4, 21, 17, 0),
        "location": "Bahen Centre, 40 St George St, Toronto",
        "description": "Structured speed-networking with finance professionals from Big 5 banks, Big 4 advisory, and buy-side firms. 10-minute rotating sessions.",
        "is_public": True,
    },
    {
        "firm_name": "CFA Society Toronto",
        "event_type": "Networking",
        "title": "CFA Society Toronto — Young Professionals Mixer",
        "date": datetime(2026, 4, 22, 18, 30),
        "location": "The Rec Room, 255 Bremner Blvd, Toronto",
        "description": "Monthly networking event for CFA candidates and charterholders under 35. Mix with investment professionals across AM, PE, and IB.",
        "is_public": True,
    },
    {
        "firm_name": "RBC Capital Markets",
        "event_type": "Info Session",
        "title": "RBC Capital Markets — Campus Recruiting Information Session",
        "date": datetime(2026, 4, 23, 17, 30),
        "location": "200 Bay St, Royal Bank Plaza, Toronto",
        "description": "Overview of RBC CM's summer analyst program across IBD, ECM, DCM, and Leveraged Finance. Q&A with analysts and associates.",
        "is_public": True,
    },
    {
        "firm_name": "OMERS",
        "event_type": "Info Session",
        "title": "OMERS — Careers in Infrastructure & Private Equity",
        "date": datetime(2026, 4, 24, 12, 0),
        "location": "OMERS HQ, 1 University Ave, Toronto",
        "description": "Learn about OMERS' Infrastructure, Private Equity, and Real Estate investment teams. Investment professionals share their day-to-day and career paths.",
        "is_public": True,
    },
    {
        "firm_name": "Boston Consulting Group",
        "event_type": "Info Session",
        "title": "BCG Toronto — Office Open House & Consulting Career Panel",
        "date": datetime(2026, 4, 25, 10, 0),
        "location": "181 Bay St, Suite 2400, Toronto",
        "description": "Tour of BCG's Toronto office, case workshop, and panel with consultants from the Financial Services and Private Equity practices.",
        "is_public": True,
    },
    # ── May 2026 ────────────────────────────────────────────────────────────
    {
        "firm_name": "Rotman Commerce Career Centre",
        "event_type": "Networking",
        "title": "Rotman Commerce Spring Career Fair 2026",
        "date": datetime(2026, 5, 1, 10, 0),
        "location": "Myhal Centre, 55 St George St, Toronto",
        "description": "Annual spring career fair with 40+ employers including Big 5 banks, Big 4 advisory, MBB consulting, pension funds, and asset managers.",
        "is_public": True,
    },
    {
        "firm_name": "Goldman Sachs",
        "event_type": "Info Session",
        "title": "Goldman Sachs Toronto — Global Markets & IBD Overview",
        "date": datetime(2026, 5, 5, 17, 0),
        "location": "222 Bay St, Suite 3400, Toronto",
        "description": "Overview of Goldman Sachs' Toronto office, covering IBD, Equities, Fixed Income, and Risk. Current analysts discuss day-to-day responsibilities.",
        "is_public": True,
    },
    {
        "firm_name": "CPP Investments",
        "event_type": "Info Session",
        "title": "CPP Investments — On-Campus Recruitment Presentation",
        "date": datetime(2026, 5, 7, 12, 0),
        "location": "Rotman Commerce, 105 St George St, Room 200",
        "description": "CPP Investments presents its Summer Analyst and New Analyst programs across Active Equities, Credit Investments, Infrastructure, and Real Assets.",
        "is_public": True,
    },
    {
        "firm_name": "Deloitte Canada",
        "event_type": "Networking",
        "title": "Deloitte Financial Advisory Networking Evening",
        "date": datetime(2026, 5, 8, 18, 0),
        "location": "Deloitte Toronto, 8 Adelaide St W, Toronto",
        "description": "Cocktail networking with Deloitte's M&A, Valuations, and Corporate Finance teams. Ideal for students targeting advisory or restructuring roles.",
        "is_public": True,
    },
    {
        "firm_name": "McKinsey & Company",
        "event_type": "Info Session",
        "title": "McKinsey Toronto — Path to Management Consulting (UofT)",
        "date": datetime(2026, 5, 13, 17, 30),
        "location": "Rotman School of Management, 105 St George St",
        "description": "McKinsey partners and associates discuss the recruiting process, case interview structure, and what makes a strong McKinsey candidate from UofT.",
        "is_public": True,
    },
    {
        "firm_name": "Bay Street Women in Finance",
        "event_type": "Networking",
        "title": "Bay Street Women in Finance — Spring Networking Luncheon",
        "date": datetime(2026, 5, 14, 12, 0),
        "location": "The National Club, 303 Bay St, Toronto",
        "description": "Annual luncheon connecting women in finance across IBD, AM, consulting, and the public sector. Keynote by a senior portfolio manager.",
        "is_public": True,
    },
    {
        "firm_name": "BMO Capital Markets",
        "event_type": "Workshop",
        "title": "BMO Capital Markets — Mock Interview & Technical Workshop",
        "date": datetime(2026, 5, 15, 9, 0),
        "location": "BMO Financial Group, 100 King St W, Toronto",
        "description": "Half-day workshop covering technical IBD interview preparation: DCF, LBO, accretion/dilution, and behavioural questions. Open to 2nd and 3rd year students.",
        "is_public": True,
    },
    {
        "firm_name": "Ontario Teachers' Pension Plan",
        "event_type": "Info Session",
        "title": "Ontario Teachers' — Careers in Infrastructure & Equities",
        "date": datetime(2026, 5, 19, 12, 0),
        "location": "5650 Yonge St, Toronto (Teachers' HQ)",
        "description": "Investment professionals from Teachers' Infrastructure, Global Equities, and Venture & Growth Equity present career paths and the recruitment process.",
        "is_public": True,
    },
    {
        "firm_name": "Scotiabank",
        "event_type": "Info Session",
        "title": "Scotiabank Global Banking & Markets — Summer Analyst Info Session",
        "date": datetime(2026, 5, 20, 17, 0),
        "location": "Scotia Plaza, 40 King St W, Toronto",
        "description": "Overview of Scotiabank GBM's summer analyst program across Fixed Income, Equities, FX, and Corporate & Investment Banking.",
        "is_public": True,
    },
    {
        "firm_name": "Brookfield Asset Management",
        "event_type": "Info Session",
        "title": "Brookfield Asset Management — Real Assets Career Panel",
        "date": datetime(2026, 5, 21, 17, 30),
        "location": "Brookfield Place, 181 Bay St, Toronto",
        "description": "Senior professionals from Brookfield's Infrastructure, Real Estate, Renewable Power, and Private Equity groups discuss investment strategies and analyst roles.",
        "is_public": True,
    },
    {
        "firm_name": "CIBC Capital Markets",
        "event_type": "Info Session",
        "title": "CIBC Capital Markets — Summer Analyst Experience Panel",
        "date": datetime(2026, 5, 27, 17, 0),
        "location": "CIBC Square, 81 Bay St, Toronto",
        "description": "Current and returning summer analysts share their experience in CIBC's IBD, ECM, Leveraged Finance, and Equity Research groups.",
        "is_public": True,
    },
    {
        "firm_name": "Rotman School of Management",
        "event_type": "Info Session",
        "title": "Rotman MBA — Finance Career Track Panel",
        "date": datetime(2026, 5, 28, 12, 0),
        "location": "Rotman School of Management, 105 St George St",
        "description": "Rotman MBA alumni in IBD, PE, AM, and consulting discuss the MBA's value in finance recruiting and how to maximise your first year.",
        "is_public": True,
    },
    # ── June 2026 ───────────────────────────────────────────────────────────
    {
        "firm_name": "UofT Career Learning Network",
        "event_type": "Workshop",
        "title": "CFA Exam Prep Workshop — Levels I & II (UofT)",
        "date": datetime(2026, 6, 3, 14, 0),
        "location": "Myhal Centre, 55 St George St, Room 380",
        "description": "Workshop covering the most tested CFA Level I and Level II topics: Fixed Income, Equity Valuation, and Ethics. Hosted by UofT CFA Society student chapter.",
        "is_public": True,
    },
    {
        "firm_name": "Bay Street Networking",
        "event_type": "Networking",
        "title": "Bay Street Spring Networking Cocktail — Finance Edition",
        "date": datetime(2026, 6, 5, 18, 30),
        "location": "Canoe Restaurant, 66 Wellington St W, 54th Floor",
        "description": "Annual spring cocktail for finance professionals and students. Over 150 attendees expected across IBD, AM, PE, consulting, and the public sector.",
        "is_public": True,
    },
    {
        "firm_name": "National Bank Financial",
        "event_type": "Info Session",
        "title": "National Bank Financial — Capital Markets Info Session",
        "date": datetime(2026, 6, 9, 17, 0),
        "location": "130 King St W, Suite 3200, Toronto",
        "description": "National Bank's IBD, Equity Research, and Fixed Income teams present on the analyst experience, deal flow, and the firm's growth strategy in Toronto.",
        "is_public": True,
    },
    {
        "firm_name": "Canadian Private Equity Forum",
        "event_type": "Networking",
        "title": "Private Equity Career Panel — Onex, Brookfield, CPP Investments",
        "date": datetime(2026, 6, 10, 17, 30),
        "location": "Gowling WLG, 1 First Canadian Place, Toronto",
        "description": "Professionals from Onex, Brookfield Private Equity, and CPPIB discuss career paths into PE, the recruiting process, and day-to-day responsibilities.",
        "is_public": True,
    },
    {
        "firm_name": "Fintech Toronto",
        "event_type": "Networking",
        "title": "Fintech Toronto 2026 — Innovation in Financial Services",
        "date": datetime(2026, 6, 12, 17, 0),
        "location": "MaRS Discovery District, 101 College St, Toronto",
        "description": "Networking event for fintech professionals, developers, and students interested in payments, open banking, crypto, and AI in financial services.",
        "is_public": True,
    },
    {
        "firm_name": "Bain & Company",
        "event_type": "Info Session",
        "title": "Bain & Company Toronto — Summer Recruiting Info Session",
        "date": datetime(2026, 6, 16, 17, 30),
        "location": "Bain & Company, 181 Bay St, Suite 3350, Toronto",
        "description": "Overview of Bain's summer associate program and full-time BA recruiting. Case practice session and Q&A with consultants from the Toronto office.",
        "is_public": True,
    },
    {
        "firm_name": "KPMG Canada",
        "event_type": "Networking",
        "title": "KPMG Deal Advisory — Networking & Careers Evening",
        "date": datetime(2026, 6, 18, 18, 0),
        "location": "KPMG Tower, Bay Adelaide Centre, 333 Bay St",
        "description": "Network with KPMG's M&A Advisory, Corporate Finance, and Valuations teams. Ideal for students targeting transaction services, restructuring, or deal roles.",
        "is_public": True,
    },
    {
        "firm_name": "Morgan Stanley",
        "event_type": "Info Session",
        "title": "Morgan Stanley Toronto — IBD Summer Analyst Preview",
        "date": datetime(2026, 6, 24, 17, 0),
        "location": "Morgan Stanley, 100 King St W, Suite 5700",
        "description": "Morgan Stanley's Toronto IBD team shares insights on the summer analyst experience, live deal exposure, and what distinguishes top performers.",
        "is_public": True,
    },
    # ── July 2026 ───────────────────────────────────────────────────────────
    {
        "firm_name": "Bay Street Recruiting Network",
        "event_type": "Workshop",
        "title": "Fall Recruiting Kickoff — Bay Street Prep Workshop",
        "date": datetime(2026, 7, 8, 9, 0),
        "location": "Rotman Commerce, 105 St George St, Toronto",
        "description": "Full-day prep workshop for fall 2026 recruiting season. Covers resume writing, networking emails, technical prep, and timeline strategy for IBD and AM roles.",
        "is_public": True,
    },
    {
        "firm_name": "UofT Finance Alumni Network",
        "event_type": "Networking",
        "title": "Summer Analyst Mid-Program Networking Mixer",
        "date": datetime(2026, 7, 14, 18, 0),
        "location": "Loose Moose, 220 Adelaide St W, Toronto",
        "description": "Mid-summer networking event for finance summer analysts across Bay Street. Connect with peers from different firms and share experiences.",
        "is_public": True,
    },
    {
        "firm_name": "UofT Alumni in Finance",
        "event_type": "Networking",
        "title": "UofT Alumni in Finance — Annual Networking Gala",
        "date": datetime(2026, 7, 17, 18, 30),
        "location": "The Omni King Edward Hotel, 37 King St E, Toronto",
        "description": "Annual black-tie optional gala connecting UofT alumni in finance with current students. Over 200 attendees from IBD, AM, PE, consulting, and government.",
        "is_public": True,
    },
    {
        "firm_name": "Rotman Commerce Career Centre",
        "event_type": "Workshop",
        "title": "Fall Recruiting Resume & Cover Letter Workshop",
        "date": datetime(2026, 7, 22, 14, 0),
        "location": "Rotman Commerce, 105 St George St, Room 140",
        "description": "One-on-one resume critiques and group cover letter workshop for fall 2026 finance recruiting. Facilitated by career advisors and second-year students.",
        "is_public": True,
    },
    # ── August 2026 ─────────────────────────────────────────────────────────
    {
        "firm_name": "Big 5 Banks",
        "event_type": "Info Session",
        "title": "Big 5 Banks Fall Recruiting Information Night",
        "date": datetime(2026, 8, 6, 17, 30),
        "location": "Myhal Centre, 55 St George St, Toronto",
        "description": "Joint recruiting event hosted by TD, RBC, BMO, Scotiabank, and CIBC. Each bank presents its fall 2026 analyst programs across IBD, Capital Markets, and AM.",
        "is_public": True,
    },
    {
        "firm_name": "Rotman Commerce Career Centre",
        "event_type": "Info Session",
        "title": "Fall 2026 Recruiting Orientation — What to Expect",
        "date": datetime(2026, 8, 13, 10, 0),
        "location": "Rotman Commerce, 105 St George St, Room 200",
        "description": "Mandatory orientation for 3rd-year students entering fall 2026 recruiting. Covers timeline, employer expectations, and career centre resources.",
        "is_public": True,
    },
    {
        "firm_name": "UofT Case Competition Club",
        "event_type": "Workshop",
        "title": "Consulting Case Competition Prep — Fall Recruiting Edition",
        "date": datetime(2026, 8, 19, 13, 0),
        "location": "Bahen Centre, 40 St George St, Room 1230",
        "description": "Intensive case prep session for MBB and Big 4 Strategy recruiting. Covers market-sizing, frameworks, and structuring a final recommendation.",
        "is_public": True,
    },
    {
        "firm_name": "EY-Parthenon",
        "event_type": "Info Session",
        "title": "EY-Parthenon Strategy — Campus Recruiting Session",
        "date": datetime(2026, 8, 25, 17, 0),
        "location": "EY Tower, 100 Adelaide St W, Toronto",
        "description": "EY-Parthenon's Strategy & Transactions team presents on the analyst experience, typical engagements, and how it compares to MBB for undergraduates.",
        "is_public": True,
    },
]
