"""
Static Canadian job postings seed.

All entries link to the firm's verified Canadian careers portal (division-filtered
where possible). Career-page URLs are stable and won't expire — unlike individual
job-posting links which disappear when a role closes.

Only Canadian locations (ON, QC, BC, AB) are included.
"""

from datetime import datetime

# Posted-at date: use a recent fixed date so they sort to the top
_NOW = datetime(2026, 4, 15, 9, 0, 0)

JOBS = [
    # ── TD Securities ──────────────────────────────────────────────────────────
    {
        "title": "Summer Analyst – Investment Banking",
        "company": "TD Securities",
        "location": "Toronto, ON",
        "url": "https://jobs.td.com/en-CA/job-search-results/?category=Investment%20Banking%20%26%20Capital%20Markets",
        "job_type": "Internship",
        "source": "TD Securities",
        "description": "Summer internship in TD Securities' Investment Banking division. Rotations across M&A, ECM, and DCM.",
        "posted_at": _NOW,
    },
    {
        "title": "Summer Analyst – Global Markets",
        "company": "TD Securities",
        "location": "Toronto, ON",
        "url": "https://jobs.td.com/en-CA/job-search-results/?category=Wholesale+Banking",
        "job_type": "Internship",
        "source": "TD Securities",
        "description": "Summer internship in TD Securities' Global Markets division. Desks include Rates, FX, and Credit.",
        "posted_at": _NOW,
    },
    # ── RBC Capital Markets ────────────────────────────────────────────────────
    {
        "title": "Summer Analyst – Investment Banking",
        "company": "RBC Capital Markets",
        "location": "Toronto, ON",
        "url": "https://jobs.rbc.com/ca/en/capital-markets",
        "job_type": "Internship",
        "source": "RBC Capital Markets",
        "description": "Summer Analyst role in RBC Capital Markets' Toronto Investment Banking division.",
        "posted_at": _NOW,
    },
    {
        "title": "Summer Analyst – Global Markets",
        "company": "RBC Capital Markets",
        "location": "Toronto, ON",
        "url": "https://jobs.rbc.com/ca/en/capital-markets",
        "job_type": "Internship",
        "source": "RBC Capital Markets",
        "description": "Summer Analyst in RBC Global Markets — Rates, Credit, and FX desks in Toronto.",
        "posted_at": _NOW,
    },
    # ── BMO Capital Markets ────────────────────────────────────────────────────
    {
        "title": "Summer Analyst – Capital Markets",
        "company": "BMO Capital Markets",
        "location": "Toronto, ON",
        "url": "https://jobs.bmo.com/ca/en/",
        "job_type": "Internship",
        "source": "BMO Capital Markets",
        "description": "Summer Analyst opportunity in BMO Capital Markets, Toronto. Coverage spans M&A, ECM, and Leveraged Finance.",
        "posted_at": _NOW,
    },
    {
        "title": "Analyst – Corporate Finance",
        "company": "BMO Capital Markets",
        "location": "Toronto, ON",
        "url": "https://jobs.bmo.com/ca/en/",
        "job_type": "Full-time",
        "source": "BMO Capital Markets",
        "description": "Full-time Analyst position in BMO's Corporate Finance group, working on Canadian M&A transactions.",
        "posted_at": _NOW,
    },
    # ── Scotiabank GBM ─────────────────────────────────────────────────────────
    {
        "title": "Summer Analyst – Global Banking & Markets",
        "company": "Scotiabank GBM",
        "location": "Toronto, ON",
        "url": "https://jobs.scotiabank.com/search/?q=global+banking+markets&location=Toronto%2C+Ontario",
        "job_type": "Internship",
        "source": "Scotiabank GBM",
        "description": "Summer Analyst role in Scotiabank's Global Banking & Markets division, Toronto.",
        "posted_at": _NOW,
    },
    # ── CIBC Capital Markets ───────────────────────────────────────────────────
    {
        "title": "Summer Analyst – Investment Banking",
        "company": "CIBC Capital Markets",
        "location": "Toronto, ON",
        "url": "https://careers.cibc.com/en-CA/job-search/?keyword=investment+banking&location=Toronto",
        "job_type": "Internship",
        "source": "CIBC Capital Markets",
        "description": "Summer Analyst at CIBC Capital Markets, Toronto. Exposure to Canadian M&A and ECM.",
        "posted_at": _NOW,
    },
    # ── National Bank Financial ────────────────────────────────────────────────
    {
        "title": "Summer Analyst – Capital Markets",
        "company": "National Bank Financial",
        "location": "Montreal, QC",
        "url": "https://emplois.nbc.ca/en/search-results?keywords=capital+markets",
        "job_type": "Internship",
        "source": "National Bank Financial",
        "description": "Summer Analyst at National Bank Financial in Montreal. Focus on Québec-based M&A and ECM transactions.",
        "posted_at": _NOW,
    },
    # ── Goldman Sachs (Toronto) ────────────────────────────────────────────────
    {
        "title": "Summer Analyst – Investment Banking Division",
        "company": "Goldman Sachs",
        "location": "Toronto, ON",
        "url": "https://www.goldmansachs.com/careers/search#ss=true&countries=Canada",
        "job_type": "Internship",
        "source": "Goldman Sachs",
        "description": "Goldman Sachs IBD Summer Analyst programme, Toronto office. Full-time conversion opportunity.",
        "posted_at": _NOW,
    },
    {
        "title": "Summer Analyst – Global Markets",
        "company": "Goldman Sachs",
        "location": "Toronto, ON",
        "url": "https://www.goldmansachs.com/careers/search#ss=true&countries=Canada",
        "job_type": "Internship",
        "source": "Goldman Sachs",
        "description": "Goldman Sachs Global Markets Summer Analyst, Toronto. Sales & Trading desks including FICC and Equities.",
        "posted_at": _NOW,
    },
    # ── Morgan Stanley (Toronto) ───────────────────────────────────────────────
    {
        "title": "Summer Analyst – Investment Banking",
        "company": "Morgan Stanley",
        "location": "Toronto, ON",
        "url": "https://www.morganstanley.com/people-opportunities/students-graduates/programs/internships",
        "job_type": "Internship",
        "source": "Morgan Stanley",
        "description": "Morgan Stanley Investment Banking Summer Analyst, Toronto. Canadian M&A and capital markets coverage.",
        "posted_at": _NOW,
    },
    # ── JPMorgan (Toronto) ─────────────────────────────────────────────────────
    {
        "title": "Summer Analyst – Investment Banking",
        "company": "JPMorgan",
        "location": "Toronto, ON",
        "url": "https://careers.jpmorgan.com/ca/en/students",
        "job_type": "Internship",
        "source": "JPMorgan",
        "description": "JPMorgan Investment Banking Summer Analyst at the Toronto office.",
        "posted_at": _NOW,
    },
    {
        "title": "Summer Analyst – Markets",
        "company": "JPMorgan",
        "location": "Toronto, ON",
        "url": "https://careers.jpmorgan.com/ca/en/students",
        "job_type": "Internship",
        "source": "JPMorgan",
        "description": "JPMorgan Markets Summer Analyst (Sales, Trading & Research) — Toronto.",
        "posted_at": _NOW,
    },
    # ── Barclays (Toronto) ─────────────────────────────────────────────────────
    {
        "title": "Summer Analyst – Investment Banking",
        "company": "Barclays",
        "location": "Toronto, ON",
        "url": "https://search.jobs.barclays/en_GB/careers#/",
        "job_type": "Internship",
        "source": "Barclays",
        "description": "Barclays Investment Banking Summer Analyst based in Toronto, Canada office.",
        "posted_at": _NOW,
    },
    # ── Citi (Toronto) ─────────────────────────────────────────────────────────
    {
        "title": "Summer Analyst – Banking, Capital Markets & Advisory",
        "company": "Citi",
        "location": "Toronto, ON",
        "url": "https://jobs.citi.com/job/toronto",
        "job_type": "Internship",
        "source": "Citi",
        "description": "Citi BCMA Summer Analyst – Canadian coverage group in Toronto.",
        "posted_at": _NOW,
    },
    # ── Canaccord Genuity ──────────────────────────────────────────────────────
    {
        "title": "Summer Analyst – Investment Banking",
        "company": "Canaccord Genuity",
        "location": "Toronto, ON",
        "url": "https://www.canaccordgenuity.com/capital-markets/careers/",
        "job_type": "Internship",
        "source": "Canaccord Genuity",
        "description": "Summer Analyst at Canaccord Genuity's Investment Banking division, Toronto. Focus on mid-market M&A and ECM.",
        "posted_at": _NOW,
    },
    # ── CPP Investments ────────────────────────────────────────────────────────
    {
        "title": "Summer Associate – Investment Management",
        "company": "CPP Investments",
        "location": "Toronto, ON",
        "url": "https://www.cppinvestments.com/careers/job-openings/",
        "job_type": "Internship",
        "source": "CPP Investments",
        "description": "CPP Investments Summer Associate – asset classes include infrastructure, private equity, and real estate.",
        "posted_at": _NOW,
    },
    {
        "title": "Investment Associate – Private Equity",
        "company": "CPP Investments",
        "location": "Toronto, ON",
        "url": "https://www.cppinvestments.com/careers/job-openings/",
        "job_type": "Full-time",
        "source": "CPP Investments",
        "description": "Full-time Investment Associate in CPP Investments' Private Equity department, Toronto.",
        "posted_at": _NOW,
    },
    # ── OMERS ──────────────────────────────────────────────────────────────────
    {
        "title": "Summer Analyst – Private Equity",
        "company": "OMERS",
        "location": "Toronto, ON",
        "url": "https://careers.omers.com/ca/en/search-results",
        "job_type": "Internship",
        "source": "OMERS",
        "description": "OMERS Private Equity Summer Analyst, Toronto. Work on direct buyout investments.",
        "posted_at": _NOW,
    },
    {
        "title": "Summer Analyst – Infrastructure",
        "company": "OMERS Infrastructure",
        "location": "Toronto, ON",
        "url": "https://careers.omers.com/ca/en/search-results",
        "job_type": "Internship",
        "source": "OMERS",
        "description": "OMERS Infrastructure Summer Analyst – global infrastructure origination and asset management.",
        "posted_at": _NOW,
    },
    # ── Ontario Teachers' Pension Plan ────────────────────────────────────────
    {
        "title": "Summer Analyst – Equities",
        "company": "Ontario Teachers' Pension Plan",
        "location": "Toronto, ON",
        "url": "https://www.otpp.com/en-ca/careers/",
        "job_type": "Internship",
        "source": "Ontario Teachers'",
        "description": "Ontario Teachers' Equities Summer Analyst – public equities investing across global markets.",
        "posted_at": _NOW,
    },
    {
        "title": "Summer Analyst – Private Capital",
        "company": "Ontario Teachers' Pension Plan",
        "location": "Toronto, ON",
        "url": "https://www.otpp.com/en-ca/careers/",
        "job_type": "Internship",
        "source": "Ontario Teachers'",
        "description": "Ontario Teachers' Private Capital Summer Analyst. PE and VC deal exposure.",
        "posted_at": _NOW,
    },
    # ── Brookfield Asset Management ───────────────────────────────────────────
    {
        "title": "Summer Analyst – Real Estate",
        "company": "Brookfield Asset Management",
        "location": "Toronto, ON",
        "url": "https://careers.brookfield.com/",
        "job_type": "Internship",
        "source": "Brookfield",
        "description": "Brookfield Real Estate group Summer Analyst, Toronto. Global REIT and direct real estate investments.",
        "posted_at": _NOW,
    },
    {
        "title": "Summer Analyst – Infrastructure",
        "company": "Brookfield Asset Management",
        "location": "Toronto, ON",
        "url": "https://careers.brookfield.com/",
        "job_type": "Internship",
        "source": "Brookfield",
        "description": "Brookfield Infrastructure Summer Analyst – origination and asset management across utilities, transport, data.",
        "posted_at": _NOW,
    },
    # ── Manulife Investment Management ────────────────────────────────────────
    {
        "title": "Summer Analyst – Public Fixed Income",
        "company": "Manulife Investment Management",
        "location": "Toronto, ON",
        "url": "https://careers.manulife.com/global/en",
        "job_type": "Internship",
        "source": "Manulife",
        "description": "Manulife Investment Management Summer Analyst on the Public Fixed Income team in Toronto.",
        "posted_at": _NOW,
    },
    # ── McKinsey & Company (Toronto) ──────────────────────────────────────────
    {
        "title": "Business Analyst – Toronto Office",
        "company": "McKinsey & Company",
        "location": "Toronto, ON",
        "url": "https://www.mckinsey.com/careers/search-jobs#country=Canada",
        "job_type": "Full-time",
        "source": "McKinsey",
        "description": "Full-time Business Analyst at McKinsey Toronto – Financial Services and Strategy practices.",
        "posted_at": _NOW,
    },
    {
        "title": "Summer Business Analyst – Toronto",
        "company": "McKinsey & Company",
        "location": "Toronto, ON",
        "url": "https://www.mckinsey.com/careers/search-jobs#country=Canada",
        "job_type": "Internship",
        "source": "McKinsey",
        "description": "McKinsey Summer Business Analyst, Toronto office. 10-week consulting internship.",
        "posted_at": _NOW,
    },
    # ── Boston Consulting Group (Toronto) ─────────────────────────────────────
    {
        "title": "Associate – Toronto",
        "company": "Boston Consulting Group",
        "location": "Toronto, ON",
        "url": "https://careers.bcg.com/job-search?keyword=associate&location=Toronto",
        "job_type": "Full-time",
        "source": "BCG",
        "description": "BCG Associate (full-time) in the Toronto office. Focus on Financial Services and Private Equity client work.",
        "posted_at": _NOW,
    },
    {
        "title": "Summer Associate – Toronto",
        "company": "Boston Consulting Group",
        "location": "Toronto, ON",
        "url": "https://careers.bcg.com/job-search?keyword=summer+associate&location=Toronto",
        "job_type": "Internship",
        "source": "BCG",
        "description": "BCG Summer Associate (MBA internship) based in Toronto.",
        "posted_at": _NOW,
    },
    # ── Bain & Company (Toronto) ──────────────────────────────────────────────
    {
        "title": "Associate Consultant – Toronto",
        "company": "Bain & Company",
        "location": "Toronto, ON",
        "url": "https://www.bain.com/careers/find-a-role/?office=Toronto",
        "job_type": "Full-time",
        "source": "Bain",
        "description": "Bain Associate Consultant in Toronto. Rotation across Financial Services, Retail, and PE practice areas.",
        "posted_at": _NOW,
    },
    {
        "title": "Summer Associate Consultant – Toronto",
        "company": "Bain & Company",
        "location": "Toronto, ON",
        "url": "https://www.bain.com/careers/find-a-role/?office=Toronto",
        "job_type": "Internship",
        "source": "Bain",
        "description": "Bain Summer Associate Consultant in Toronto – 10-week internship with full-time offer potential.",
        "posted_at": _NOW,
    },
    # ── Deloitte (Canada) ──────────────────────────────────────────────────────
    {
        "title": "Analyst – Financial Advisory (M&A)",
        "company": "Deloitte",
        "location": "Toronto, ON",
        "url": "https://jobs2.deloitte.com/ca/en/search-results?keywords=financial+advisory",
        "job_type": "Full-time",
        "source": "Deloitte",
        "description": "Deloitte Financial Advisory Analyst – M&A transaction support and valuations, Toronto.",
        "posted_at": _NOW,
    },
    {
        "title": "Summer Analyst – Financial Advisory",
        "company": "Deloitte",
        "location": "Toronto, ON",
        "url": "https://jobs2.deloitte.com/ca/en/search-results?keywords=summer+analyst",
        "job_type": "Internship",
        "source": "Deloitte",
        "description": "Deloitte Financial Advisory Summer Analyst, Toronto. Exposure to M&A due diligence and valuations.",
        "posted_at": _NOW,
    },
    # ── KPMG (Canada) ──────────────────────────────────────────────────────────
    {
        "title": "Analyst – Deal Advisory",
        "company": "KPMG",
        "location": "Toronto, ON",
        "url": "https://careers.kpmg.ca/",
        "job_type": "Full-time",
        "source": "KPMG",
        "description": "KPMG Deal Advisory Analyst – M&A valuations and transaction services in Toronto.",
        "posted_at": _NOW,
    },
    # ── EY (Canada) ────────────────────────────────────────────────────────────
    {
        "title": "Analyst – Strategy and Transactions",
        "company": "EY-Parthenon",
        "location": "Toronto, ON",
        "url": "https://careers.ey.com/ey/search#country=CA&keyword=strategy",
        "job_type": "Full-time",
        "source": "EY",
        "description": "EY-Parthenon Strategy and Transactions Analyst in Toronto. Commercial due diligence and corporate strategy.",
        "posted_at": _NOW,
    },
    # ── PwC (Canada) ───────────────────────────────────────────────────────────
    {
        "title": "Associate – Deals (M&A Advisory)",
        "company": "PwC Canada",
        "location": "Toronto, ON",
        "url": "https://www.pwc.com/ca/en/careers.html",
        "job_type": "Full-time",
        "source": "PwC",
        "description": "PwC Deals Associate in Toronto – financial due diligence, valuations, and M&A advisory.",
        "posted_at": _NOW,
    },
    # ── Lazard (Toronto) ───────────────────────────────────────────────────────
    {
        "title": "Analyst – Investment Banking",
        "company": "Lazard",
        "location": "Toronto, ON",
        "url": "https://www.lazard.com/career-opportunities/",
        "job_type": "Full-time",
        "source": "Lazard",
        "description": "Lazard Investment Banking Analyst in Toronto – M&A and restructuring advisory across Canadian corporates.",
        "posted_at": _NOW,
    },
    # ── Rothschild & Co (Toronto) ──────────────────────────────────────────────
    {
        "title": "Analyst – Global Advisory",
        "company": "Rothschild & Co",
        "location": "Toronto, ON",
        "url": "https://www.rothschildandco.com/en/careers/",
        "job_type": "Full-time",
        "source": "Rothschild & Co",
        "description": "Rothschild & Co Global Advisory Analyst in Toronto. Independent M&A and restructuring mandates.",
        "posted_at": _NOW,
    },
    # ── CIBC Mellon / Equity Research ─────────────────────────────────────────
    {
        "title": "Summer Analyst – Equity Research",
        "company": "RBC Capital Markets",
        "location": "Toronto, ON",
        "url": "https://jobs.rbc.com/ca/en/capital-markets",
        "job_type": "Internship",
        "source": "RBC Capital Markets",
        "description": "RBC Capital Markets Equity Research Summer Analyst – coverage of Canadian industrials, financials, and energy.",
        "posted_at": _NOW,
    },
]
