from datetime import date

NEWS_ARTICLES = [
    # Deals
    {
        "title": "RBC Capital Markets Advises on $4.2B Rogers Infrastructure Sale",
        "url": "https://financialpost.com/news/rbc-rogers-infrastructure-2026",
        "source": "Financial Post",
        "summary": "RBC Capital Markets acted as lead financial advisor to Rogers Communications in the $4.2 billion sale of its towers infrastructure to Brookfield Infrastructure Partners, one of the largest telecom deals in Canadian history.",
        "published_at": date(2026, 3, 15),
        "category": "Deals",
    },
    {
        "title": "TD Securities and Goldman Sachs Lead $2.8B Maple Leaf Foods LBO",
        "url": "https://financialpost.com/investing/maple-leaf-foods-lbo-td-goldman-2026",
        "source": "Financial Post",
        "summary": "A consortium led by Ontario Teachers' Pension Plan and CPPIB has agreed to acquire Maple Leaf Foods in a $2.8 billion leveraged buyout, with TD Securities and Goldman Sachs acting as joint lead arrangers on the debt financing.",
        "published_at": date(2026, 3, 8),
        "category": "Deals",
    },
    {
        "title": "Brookfield Asset Management Closes $15B Infrastructure Fund IV",
        "url": "https://financialpost.com/investing/brookfield-infrastructure-fund-iv-close-2026",
        "source": "Financial Post",
        "summary": "Brookfield Asset Management announced the final close of its fourth flagship infrastructure fund at $15 billion, surpassing its $12 billion target on strong demand from sovereign wealth funds and North American pension plans.",
        "published_at": date(2026, 2, 20),
        "category": "Deals",
    },
    {
        "title": "Scotiabank Wins Mandate on $1.9B Pembina Pipeline Secondary Offering",
        "url": "https://www.theglobeandmail.com/business/scotiabank-pembina-pipeline-secondary-2026",
        "source": "Globe and Mail Business",
        "summary": "Scotiabank Global Banking and Markets has been named sole bookrunner on Pembina Pipeline Corporation's $1.9 billion bought deal secondary offering, with proceeds earmarked for the company's net-zero LNG infrastructure expansion.",
        "published_at": date(2026, 3, 1),
        "category": "Deals",
    },
    {
        "title": "Fairfax Financial Acquires Allied World Stake for $900M",
        "url": "https://baystreetbull.com/fairfax-allied-world-acquisition-2026",
        "source": "Bay Street Bull",
        "summary": "Prem Watsa's Fairfax Financial Holdings has agreed to acquire an additional 12% stake in Allied World Assurance for $900 million, raising its ownership to a controlling 87% and signalling renewed appetite for global insurance M&A.",
        "published_at": date(2026, 2, 14),
        "category": "Deals",
    },
    # Bay Street
    {
        "title": "Bay Street Bonuses Rise 18% as Deal Activity Rebounds in 2026",
        "url": "https://baystreetbull.com/bay-street-bonuses-2026-rebound",
        "source": "Bay Street Bull",
        "summary": "Canadian investment banks are set to pay out the largest bonus pool since 2021, with total compensation rising an estimated 18% year-over-year as equity capital markets, M&A advisory, and leveraged finance all posted strong first quarters.",
        "published_at": date(2026, 3, 22),
        "category": "Bay Street",
    },
    {
        "title": "RBC Tops Canadian Equity Underwriting League Tables for Fifth Straight Year",
        "url": "https://www.theglobeandmail.com/business/rbc-equity-underwriting-league-tables-2026",
        "source": "Globe and Mail Business",
        "summary": "RBC Capital Markets has retained its top position in the Canadian equity underwriting league tables for the fifth consecutive year, capturing a 28% market share in a year that saw total ECM issuance reach $48 billion.",
        "published_at": date(2026, 3, 18),
        "category": "Bay Street",
    },
    {
        "title": "CIBC Hires 40 Junior Bankers Ahead of Anticipated ECM Surge",
        "url": "https://financialpost.com/news/cibc-junior-banker-hiring-2026",
        "source": "Financial Post",
        "summary": "CIBC Capital Markets is expanding its investment banking division with 40 new analyst and associate hires across its Toronto, Calgary, and Vancouver offices, anticipating a wave of energy and technology IPOs in the second half of 2026.",
        "published_at": date(2026, 2, 28),
        "category": "Bay Street",
    },
    {
        "title": "Canaccord Genuity Expands Mining Finance Team with Six Senior Hires",
        "url": "https://baystreetbull.com/canaccord-mining-finance-hires-2026",
        "source": "Bay Street Bull",
        "summary": "Canaccord Genuity has recruited six senior mining finance professionals from BMO and National Bank as it looks to challenge the big banks in a sector that produced over $6 billion in equity financings last year.",
        "published_at": date(2026, 2, 5),
        "category": "Bay Street",
    },
    # Markets
    {
        "title": "TSX Composite Hits Record High as Energy and Financials Lead",
        "url": "https://www.theglobeandmail.com/business/tsx-record-high-energy-financials-2026",
        "source": "Globe and Mail Business",
        "summary": "The S&P/TSX Composite Index closed at a new all-time high of 27,843 on Thursday, led by outsized gains in the energy and financial services sectors as WTI crude oil climbed above $85 per barrel and big bank earnings topped analyst estimates.",
        "published_at": date(2026, 3, 27),
        "category": "Markets",
    },
    {
        "title": "Canadian Dollar Strengthens to 0.76 USD on Commodity Rally",
        "url": "https://financialpost.com/markets/canadian-dollar-commodity-rally-2026",
        "source": "Financial Post",
        "summary": "The Canadian dollar advanced to 76.4 U.S. cents — its strongest level in 14 months — as surging oil, gold, and potash prices bolstered the outlook for Canadian exports and prompted traders to pare back short positions on the loonie.",
        "published_at": date(2026, 3, 25),
        "category": "Markets",
    },
    {
        "title": "Gold Breaks $2,800/oz as Central Banks Accelerate Reserve Diversification",
        "url": "https://feeds.marketwatch.com/gold-2800-central-banks-2026",
        "source": "MarketWatch",
        "summary": "Spot gold surpassed $2,800 per troy ounce for the first time, driven by accelerating central bank purchases and safe-haven demand amid uncertainty over U.S. fiscal policy. Canadian miners Agnico Eagle and Barrick Gold surged 7% and 5% respectively.",
        "published_at": date(2026, 3, 19),
        "category": "Markets",
    },
    {
        "title": "S&P 500 Posts Best Quarter Since 2019 on AI Earnings Beat",
        "url": "https://feeds.bloomberg.com/markets/sp500-best-quarter-2026",
        "source": "Bloomberg Markets",
        "summary": "The S&P 500 index gained 12.4% in the first quarter of 2026, its best quarterly performance in seven years, as technology companies reported earnings that significantly exceeded consensus estimates on the back of enterprise AI adoption.",
        "published_at": date(2026, 4, 1),
        "category": "Markets",
    },
    # Macro / Economy
    {
        "title": "Bank of Canada Holds Rate at 3.25%, Signals One More Cut in 2026",
        "url": "https://www.bankofcanada.ca/press-release/rate-decision-march-2026",
        "source": "Bank of Canada",
        "summary": "The Bank of Canada held its overnight rate at 3.25% at its March meeting, citing persistent shelter inflation and a resilient labour market. Governor Tiff Macklem signalled that one further 25 basis-point cut remains likely before year-end if inflation continues to moderate.",
        "published_at": date(2026, 3, 12),
        "category": "Macro",
    },
    {
        "title": "Canada Adds 52,000 Jobs in February, Unemployment Steady at 6.1%",
        "url": "https://financialpost.com/economy/canada-jobs-february-2026",
        "source": "Financial Post",
        "summary": "Statistics Canada reported the Canadian economy added 52,000 net new jobs in February, topping forecasts of 35,000, with the unemployment rate holding at 6.1%. Full-time employment drove the majority of gains, concentrated in professional services and construction.",
        "published_at": date(2026, 3, 7),
        "category": "Macro",
    },
    {
        "title": "Federal Budget 2026: Ottawa Posts Smaller-Than-Expected $19B Deficit",
        "url": "https://www.theglobeandmail.com/politics/federal-budget-2026-deficit",
        "source": "Globe and Mail Business",
        "summary": "Finance Minister Chrystia Freeland tabled the 2026 federal budget projecting a $19.3 billion deficit, narrower than the $24 billion forecast in the fall economic statement, supported by stronger corporate tax revenues and lower debt servicing costs.",
        "published_at": date(2026, 3, 25),
        "category": "Macro",
    },
    {
        "title": "Canada CPI Eases to 2.1% in February, Core Inflation Stickier at 2.8%",
        "url": "https://financialpost.com/economy/canada-cpi-february-2026",
        "source": "Financial Post",
        "summary": "Canada's annual inflation rate fell to 2.1% in February from 2.4% in January, driven by lower gasoline prices, but the Bank of Canada's preferred core measures remained at 2.8%, suggesting underlying price pressures have yet to fully dissipate.",
        "published_at": date(2026, 3, 19),
        "category": "Macro",
    },
    {
        "title": "CPPIB Reports 9.8% Annual Return, AUM Surpasses $670B",
        "url": "https://www.theglobeandmail.com/business/cppib-annual-return-2026",
        "source": "Globe and Mail Business",
        "summary": "The Canada Pension Plan Investment Board reported a net return of 9.8% for the fiscal year ending March 2026, growing its assets under management to a record $671 billion, driven by strong performance in its private equity and infrastructure portfolios.",
        "published_at": date(2026, 4, 3),
        "category": "Macro",
    },
    {
        "title": "Big Six Banks Report Combined $16.4B Q1 Profit as Provisions Decline",
        "url": "https://baystreetbull.com/big-six-banks-q1-profits-2026",
        "source": "Bay Street Bull",
        "summary": "Canada's six largest banks reported a combined $16.4 billion in first-quarter net income, up 14% year-over-year, as falling provisions for credit losses offset modest net interest margin compression. TD, RBC, and BMO all beat consensus EPS estimates.",
        "published_at": date(2026, 3, 4),
        "category": "Bay Street",
    },
    {
        "title": "Shopify Dual-Lists on TSX, Adds $12B to Canadian Market Cap",
        "url": "https://baystreetbull.com/shopify-tsx-dual-list-2026",
        "source": "Bay Street Bull",
        "summary": "Shopify Inc. completed its secondary listing on the Toronto Stock Exchange, adding approximately $12 billion to the S&P/TSX Composite's market capitalisation and giving Canadian institutional investors direct domestic access to the country's most valuable technology company.",
        "published_at": date(2026, 2, 10),
        "category": "Markets",
    },
    {
        "title": "Ontario Teachers' Pension Plan Takes $500M Stake in Fintech Wealthsimple",
        "url": "https://financialpost.com/investing/teachers-wealthsimple-investment-2026",
        "source": "Financial Post",
        "summary": "Ontario Teachers' Pension Plan has led a $500 million growth equity round in Wealthsimple, valuing the Toronto-based fintech at $7.2 billion and setting the stage for a potential TSX IPO as early as 2027.",
        "published_at": date(2026, 1, 28),
        "category": "Deals",
    },
]
